// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender_id, content, project_id, receiver_id)
VALUES ($1, $2, $3, $4)
RETURNING id, sender_id, content, project_id, receiver_id, created_at
`

type CreateMessageParams struct {
	SenderID   int64
	Content    string
	ProjectID  pgtype.Int8
	ReceiverID pgtype.Int8
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SenderID,
		arg.Content,
		arg.ProjectID,
		arg.ReceiverID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.Content,
		&i.ProjectID,
		&i.ReceiverID,
		&i.CreatedAt,
	)
	return i, err
}

const getDirectMessages = `-- name: GetDirectMessages :many
SELECT m.id, m.sender_id, m.content, m.receiver_id, m.created_at, u.email as sender_email
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE (m.sender_id = $1 AND m.receiver_id = $2)
   OR (m.sender_id = $2 AND m.receiver_id = $1)
ORDER BY m.created_at ASC
`

type GetDirectMessagesParams struct {
	SenderID   int64
	ReceiverID pgtype.Int8
}

type GetDirectMessagesRow struct {
	ID          int64
	SenderID    int64
	Content     string
	ReceiverID  pgtype.Int8
	CreatedAt   pgtype.Timestamptz
	SenderEmail string
}

func (q *Queries) GetDirectMessages(ctx context.Context, arg GetDirectMessagesParams) ([]GetDirectMessagesRow, error) {
	rows, err := q.db.Query(ctx, getDirectMessages, arg.SenderID, arg.ReceiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDirectMessagesRow
	for rows.Next() {
		var i GetDirectMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Content,
			&i.ReceiverID,
			&i.CreatedAt,
			&i.SenderEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectMessages = `-- name: GetProjectMessages :many
SELECT m.id, m.sender_id, m.content, m.project_id, m.created_at, u.email as sender_email
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.project_id = $1
ORDER BY m.created_at ASC
`

type GetProjectMessagesRow struct {
	ID          int64
	SenderID    int64
	Content     string
	ProjectID   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
	SenderEmail string
}

func (q *Queries) GetProjectMessages(ctx context.Context, projectID pgtype.Int8) ([]GetProjectMessagesRow, error) {
	rows, err := q.db.Query(ctx, getProjectMessages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectMessagesRow
	for rows.Next() {
		var i GetProjectMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Content,
			&i.ProjectID,
			&i.CreatedAt,
			&i.SenderEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
