// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
WITH inserted AS (
    INSERT INTO projects (name, description, owner_id)
    VALUES ($1, $2, $3)
    RETURNING id, name, description, owner_id, created_at
)
SELECT 
    i.id, 
    i.name, 
    i.description, 
    i.owner_id, 
    i.created_at,
    u.email AS owner_name
FROM inserted i
JOIN users u ON i.owner_id = u.id
`

type CreateProjectParams struct {
	Name        string
	Description pgtype.Text
	OwnerID     int64
}

type CreateProjectRow struct {
	ID          int64
	Name        string
	Description pgtype.Text
	OwnerID     int64
	CreatedAt   pgtype.Timestamptz
	OwnerName   string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.Description, arg.OwnerID)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.OwnerName,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1 AND owner_id = $2
`

type DeleteProjectParams struct {
	ID      int64
	OwnerID int64
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OwnerID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, owner_id, created_at FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, owner_id, created_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT 
    p.id, 
    p.name, 
    p.description, 
    p.owner_id, 
    p.created_at,
    u.email AS owner_name
FROM projects p
LEFT JOIN users u ON p.owner_id = u.id
WHERE p.owner_id = $1 
   OR p.id IN (SELECT project_id FROM project_users WHERE user_id = $1)
ORDER BY p.created_at ASC
`

type ListProjectsByOwnerRow struct {
	ID          int64
	Name        string
	Description pgtype.Text
	OwnerID     int64
	CreatedAt   pgtype.Timestamptz
	OwnerName   pgtype.Text
}

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID int64) ([]ListProjectsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByOwnerRow
	for rows.Next() {
		var i ListProjectsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET name = $2,
    description = $3
WHERE id = $1
`

type UpdateProjectParams struct {
	ID          int64
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	return err
}
