// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToProject = `-- name: AddUserToProject :one
INSERT INTO project_users (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, project_id, user_id, role
`

type AddUserToProjectParams struct {
	ProjectID int64
	UserID    int64
	Role      pgtype.Text
}

func (q *Queries) AddUserToProject(ctx context.Context, arg AddUserToProjectParams) (ProjectUser, error) {
	row := q.db.QueryRow(ctx, addUserToProject, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectUser
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const checkSharedProject = `-- name: CheckSharedProject :one
SELECT EXISTS (
    SELECT 1 
    FROM project_users pu1
    JOIN project_users pu2 ON pu1.project_id = pu2.project_id
    WHERE pu1.user_id = $1 AND pu2.user_id = $2
) AS shared
`

type CheckSharedProjectParams struct {
	SenderID   int64
	ReceiverID int64
}

func (q *Queries) CheckSharedProject(ctx context.Context, arg CheckSharedProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSharedProject, arg.SenderID, arg.ReceiverID)
	var shared bool
	err := row.Scan(&shared)
	return shared, err
}

const listUsersInProject = `-- name: ListUsersInProject :many
SELECT 
    u.id, 
    u.email, 
    CASE 
        WHEN p.owner_id = u.id THEN 'owner'::text
        ELSE pu.role
    END AS role
FROM users u
JOIN project_users pu ON u.id = pu.user_id
JOIN projects p ON pu.project_id = p.id
WHERE pu.project_id = $1
`

type ListUsersInProjectRow struct {
	ID    int64
	Email string
	Role  interface{}
}

func (q *Queries) ListUsersInProject(ctx context.Context, projectID int64) ([]ListUsersInProjectRow, error) {
	rows, err := q.db.Query(ctx, listUsersInProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersInProjectRow
	for rows.Next() {
		var i ListUsersInProjectRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromProject = `-- name: RemoveUserFromProject :exec
DELETE FROM project_users
WHERE project_id = $1 AND user_id = $2
`

type RemoveUserFromProjectParams struct {
	ProjectID int64
	UserID    int64
}

func (q *Queries) RemoveUserFromProject(ctx context.Context, arg RemoveUserFromProjectParams) error {
	_, err := q.db.Exec(ctx, removeUserFromProject, arg.ProjectID, arg.UserID)
	return err
}
