// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, status, assigned_to)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, title, description, status, assigned_to, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   int64
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	AssignedTo  pgtype.Int8
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssignedTo,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const listTasksForProject = `-- name: ListTasksForProject :many
SELECT id, project_id, title, description, status, assigned_to, created_at, updated_at
FROM tasks
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTasksForProject(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2,
    description = $3,
    status = $4,
    assigned_to = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, description, status, assigned_to, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          int64
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	AssignedTo  pgtype.Int8
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssignedTo,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
