// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO task_attachments (
    task_id, 
    user_id, 
    file_name, 
    file_size,
    file_key, 
    file_url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, task_id, user_id, file_name, file_key, file_url, created_at, file_size
`

type CreateAttachmentParams struct {
	TaskID   int64
	UserID   int64
	FileName string
	FileSize int64
	FileKey  string
	FileUrl  string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (TaskAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.TaskID,
		arg.UserID,
		arg.FileName,
		arg.FileSize,
		arg.FileKey,
		arg.FileUrl,
	)
	var i TaskAttachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.FileName,
		&i.FileKey,
		&i.FileUrl,
		&i.CreatedAt,
		&i.FileSize,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM task_attachments 
WHERE id = $1
`

// For when a user wants to remove an attachment
func (q *Queries) DeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, task_id, user_id, file_name, file_key, file_url, created_at, file_size FROM task_attachments WHERE id = $1
`

// Useful for verifying ownership before deletion
func (q *Queries) GetAttachmentByID(ctx context.Context, id int64) (TaskAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i TaskAttachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.FileName,
		&i.FileKey,
		&i.FileUrl,
		&i.CreatedAt,
		&i.FileSize,
	)
	return i, err
}

const getAttachmentsByTask = `-- name: GetAttachmentsByTask :many
SELECT 
    id, 
    task_id, 
    user_id, 
    file_name, 
    file_size,
    file_url, 
    created_at
FROM task_attachments 
WHERE task_id = $1 
ORDER BY created_at DESC
`

type GetAttachmentsByTaskRow struct {
	ID        int64
	TaskID    int64
	UserID    int64
	FileName  string
	FileSize  int64
	FileUrl   string
	CreatedAt pgtype.Timestamptz
}

// This will be useful for showing a list of files on the task page
func (q *Queries) GetAttachmentsByTask(ctx context.Context, taskID int64) ([]GetAttachmentsByTaskRow, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttachmentsByTaskRow
	for rows.Next() {
		var i GetAttachmentsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.FileName,
			&i.FileSize,
			&i.FileUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
